# Generated by Django 3.2.3 on 2021-05-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_animals', models.CharField(choices=[('CT', 'Cat'), ('DG', 'Dog'), ('PT', 'Parrot')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('info', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='pets_photo')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.breed')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.kind')),
            ],
        ),
    ]
