# Generated by Django 3.2.3 on 2021-05-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='kind_of_animals',
            field=models.CharField(choices=[('CT', 'Cat'), ('DG', 'Dog'), ('PT', 'Parrot')], max_length=2, verbose_name='Вид животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=20, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.breed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='info',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.kind', verbose_name='Вид животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Кличка'),
        ),
    ]
