# Generated by Django 3.2.3 on 2021-05-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20210525_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kind',
            old_name='kind_of_animals',
            new_name='kind_of_animal',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='kind',
        ),
        migrations.AddField(
            model_name='breed',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.kind', verbose_name='Вид животного'),
        ),
    ]
